pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                echo 'Récupération du code depuis GitHub'
                checkout scm
            }
        }

        stage('Backend - Tests') {
            steps {
                echo 'Lancement des tests backend'
                dir('backend/backend') {
                    bat 'mvn test'
                }
            }
        }

        stage('Backend - Build') {
            steps {
                echo 'Build du backend Spring Boot'
                dir('backend/backend') {
                    bat 'mvn clean package'
                }
            }
        }

        stage('Frontend - Build') {
            steps {
                echo 'Build du frontend Angular'
                dir('helpdesk-front') {
                    bat 'npm install'
                    bat 'npm run build'
                }
            }
        }
    }

    post {
        success {
            echo 'CI/CD terminé avec succès'
        }
        failure {
            echo 'Erreur dans le pipeline CI/CD'
        }
    }
}
